### ISSUE TITLE
Item drops and missing recipe?

### ISSUE THREAD

**Issue by ghost** [AtlanteFr/Variety#3]
Hi,

By looking at the recipes, I see following Items without drop or recipe.

"variety:tropical_leaves_1" and "variety:tropical_leaves_2" droping Unknown Item, but I guess "variety:tropical_rainforest_sapling" should be dropped by the leaves, but that is not the case, same with "variety:dorwinion_leaves" and "variety:dorwinion_sapling".
"variety:cypress_leaves_1", "variety:cypress_leaves_2" and "variety:bambooforest_leaves" dropping Unknown Items, but I don't find the saplings in the recipe list.

Now to the Items without recipes, and these are
variety:tatami_simple
variety:japanese_tatami
variety:japanese_lamp
variety:japanese_trapdoor
doors:japanese_door
xpanes:variety:japanese_small_wall_flat_flat

Thats all.

**Comment by atlante01** [comment]
Ty, i'll correct it.

**Comment by ghost** [comment]
I'm sorry, I missed one more Item that's not having an recipe >.<

variety:mushroom_bowl
